databases:
  - name: railsdb
    databaseName: railsdb_vnbb
    user: railsdb_vnbb_user

services:
  - type: web
    name: spendlog
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railsdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
